FROM node:20-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/build ./build
RUN npm ci --only=production
USER node
CMD [ "node", "build/index.js" ]
